import type { NextPage } from "next";
import Head from "next/head";
import Calendar from "../components/calendar";
import styles from "../styles/Home.module.css";

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        calendar
        <Calendar />
      </main>
    </div>
  );
};

export default Test;
