import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import MyForm, { FilterData } from "../components/Form";
import styles from "../styles/Home.module.css";

const Test: NextPage = () => {
  const router = useRouter();
  const query = router.query;
  const [filterData, setFilterData] = useState<FilterData>();

  useEffect(() => {
    router.isReady &&
      setFilterData(() => {
        const newFilter: FilterData = [
          {
            type: "text",
            name: "name",
            selectedValue: query?.name as string,
          },
          {
            type: "checkbox",
            name: "bankAccount",
            selectedValue: query?.bankAccount as string,
          },
          {
            type: "checkbox",
            name: "job",
            selectedValue: query?.job as string,
          },
        ];
        return newFilter;
      });
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MyForm filterData={filterData} />
      </main>
    </div>
  );
};

export default Test;
